forky update

diff --git a/debian/init-d-script b/debian/init-d-script
--- a/debian/init-d-script
+++ b/debian/init-d-script
@@ -22,7 +22,7 @@ is_call_implemented() {
 }
 
 do_usage() {
-	if is_call_implemented do_reload ; then
+	if is_call_implemented do_reload; then
 		echo "Usage: $SCRIPTNAME {start|stop|status|reload|restart|try-restart|force-reload}" >&2
 	else
 		echo "Usage: $SCRIPTNAME {start|stop|status|restart|try-restart|force-reload}" >&2
@@ -32,11 +32,32 @@ do_usage() {
 call() {
 	cmd="$1"
 	shift
-	if is_call_implemented ${cmd}_override ; then
-	    ${cmd}_override "$@"
+	if is_call_implemented ${cmd}_override; then
+		${cmd}_override "$@"
 	else
-            ${cmd} "$@"
-        fi
+		${cmd} "$@"
+	fi
+}
+
+#
+# Support for oneshot services
+#
+oneshot() {
+	[ "$TYPE" = oneshot ] || return
+	case $1 in
+		start-pre) [ -f /run/$NAME.oneshot ] && exit ;;
+		start-post) touch /run/$NAME.oneshot ;;
+		stop-pre) [ ! -f /run/$NAME.oneshot ] && exit ;;
+		stop-post) rm -f /run/$NAME.oneshot ;;
+		status)
+			if [ -f /run/$NAME.oneshot ]; then
+				log_success_msg "$NAME (oneshot) has been run"
+			else
+				log_failure_msg "$NAME (oneshot) has not been run"
+			fi
+			;;
+		*) echo "ERROR: invalid oneshot request: $1" >&2 ;;
+	esac
 }
 
 #
@@ -44,32 +65,29 @@ call() {
 #
 
 do_start_cmd() {
-	if [ "$SETPRIV_ARGS" ] ; then
-	    if ! PATH=/bin:/usr/bin command -v setpriv  > /dev/null 2>&1 ; then
-	       echo "WARNING: setpriv not available, ignoring SETPRIV_ARGS" >&2
-	       unset SETPRIV_ARGS
-	    fi
-	fi
 	${SETPRIV_ARGS:+setpriv $SETPRIV_ARGS} start-stop-daemon --start --quiet \
-	    ${PIDFILE:+--pidfile "$PIDFILE"} \
-	    ${COMMAND_NAME:+--name "$COMMAND_NAME"} \
-	    ${DAEMON:+--exec "$DAEMON"} $START_ARGS -- $DAEMON_ARGS
+		${PIDFILE:+--pidfile "$PIDFILE"} \
+		${COMMAND_NAME:+--name "$COMMAND_NAME"} \
+		${DAEMON:+--exec "$DAEMON"} $START_ARGS -- $DAEMON_ARGS
 }
 
-do_start()
-{
-	if is_call_implemented do_start_prepare ; then
+do_start() {
+	oneshot start-pre
+	if is_call_implemented do_start_prepare; then
 		call do_start_prepare
 	fi
 	log_daemon_msg "Starting $DESC" "$NAME"
 	call do_start_cmd
 	retval=$?
-	if [ "$retval" = 1 ] && [ no != "$VERBOSE" ] ; then
+	if [ "$retval" = 0 ]; then
+		oneshot start-post
+	fi
+	if [ "$retval" = 1 ] && [ no != "$VERBOSE" ]; then
 		log_progress_msg "is already running"
 	fi
-	retval=$(( $retval > 1 ))
+	retval=$((retval > 1))
 	vlog_end_msg $retval
-	if is_call_implemented do_start_cleanup ; then
+	if is_call_implemented do_start_cleanup; then
 		call do_start_cleanup
 	fi
 	return $retval
@@ -81,10 +99,10 @@ do_start()
 
 do_stop_cmd() {
 	start-stop-daemon --stop --quiet \
-	    --retry=CONT/0/TERM/30/KILL/5 \
-	    ${PIDFILE:+--pidfile "$PIDFILE"} \
-	    ${COMMAND_NAME:+--name "$COMMAND_NAME"} \
-	    ${DAEMON:+--exec "$DAEMON"} $STOP_ARGS
+		--retry=CONT/0/TERM/30/KILL/5 \
+		${PIDFILE:+--pidfile "$PIDFILE"} \
+		${COMMAND_NAME:+--name "$COMMAND_NAME"} \
+		${DAEMON:+--exec "$DAEMON"} $STOP_ARGS
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
@@ -93,9 +111,9 @@ do_stop_cmd() {
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	if [ -n "$DAEMON" ] ; then
+	if [ -n "$DAEMON" ]; then
 		start-stop-daemon --stop --quiet --oknodo \
-		    --retry=0/30/KILL/5 --exec "$DAEMON" $STOP_ARGS
+			--retry=0/30/KILL/5 --exec "$DAEMON" $STOP_ARGS
 		[ "$?" = 2 ] && return 2
 	fi
 	# Many daemons don't delete their pidfiles when they exit.
@@ -103,38 +121,41 @@ do_stop_cmd() {
 	return $RETVAL
 }
 
-do_stop()
-{
-	if is_call_implemented do_stop_prepare ; then
+do_stop() {
+	oneshot stop-pre
+	if is_call_implemented do_stop_prepare; then
 		call do_stop_prepare
 	fi
 	vlog_daemon_msg "Stopping $DESC" "$NAME"
 	call do_stop_cmd
 	retval=$?
-	if [ "$retval" = 1 ] && [ no != "$VERBOSE" ] ; then
+	# Oneshot stop is unconditional
+	oneshot stop-post
+	if [ "$retval" = 1 ] && [ no != "$VERBOSE" ] &&
+		[ "$TYPE" != oneshot ]; then
 		log_progress_msg "is not running"
 	fi
-	retval=$(( $retval > 1 ))
+	retval=$((retval > 1))
 	vlog_end_msg $retval
-	if is_call_implemented do_stop_cleanup ; then
+	if is_call_implemented do_stop_cleanup; then
 		call do_stop_cleanup
 	fi
 	return $retval
 }
 
 do_restart() {
-	if is_call_implemented do_restart_prepare ; then
+	if is_call_implemented do_restart_prepare; then
 		call do_restart_prepare
 	fi
 	vlog_daemon_msg "Restarting $DESC" "$NAME"
 	call do_stop_cmd
-	retval=$(( $? > 1 ))
-	if [ $retval -eq 0 ] ; then
+	retval=$(($? > 1))
+	if [ $retval -eq 0 ]; then
 		call do_start_cmd
-		retval=$(( $? > 1 ))
+		retval=$(($? > 1))
 	fi
 	vlog_end_msg $retval
-	if is_call_implemented do_restart_cleanup ; then
+	if is_call_implemented do_restart_cleanup; then
 		call do_restart_cleanup
 	fi
 	return $retval
@@ -142,14 +163,14 @@ do_restart() {
 
 # Wrapper for do_reload_cmd
 do_reload_wrapper() {
-	if is_call_implemented do_reload_prepare ; then
+	if is_call_implemented do_reload_prepare; then
 		call do_reload_prepare
 	fi
 	vlog_daemon_msg "Reloading $DESC configuration files" "$NAME"
 	call do_reload_cmd
-	retval=$(( $? != 0 ))
+	retval=$(($? != 0))
 	vlog_end_msg $retval
-	if is_call_implemented do_reload_cleanup ; then
+	if is_call_implemented do_reload_cleanup; then
 		call do_reload_cleanup
 	fi
 	return $retval
@@ -158,9 +179,9 @@ do_reload_wrapper() {
 # To enable this function, RELOAD_SIGNAL should be set to the kill signal
 do_reload_signal() {
 	start-stop-daemon --stop --signal $RELOAD_SIGNAL --quiet \
-	    ${PIDFILE:+--pidfile "$PIDFILE"} \
-	    ${COMMAND_NAME:+--name "$COMMAND_NAME"} \
-	    ${DAEMON:+--exec "$DAEMON"} $RELOAD_ARGS
+		${PIDFILE:+--pidfile "$PIDFILE"} \
+		${COMMAND_NAME:+--name "$COMMAND_NAME"} \
+		${DAEMON:+--exec "$DAEMON"} $RELOAD_ARGS
 }
 
 # Deprecated: use RELOAD_SIGNAL instead for newer scripts
@@ -173,24 +194,28 @@ do_reload_sigusr1() {
 }
 
 do_status() {
-	status_of_proc ${PIDFILE:+-p "$PIDFILE"} "${DAEMON:-none}" "$NAME"
+	if [ "$TYPE" = oneshot ]; then
+		oneshot status
+	else
+		status_of_proc ${PIDFILE:+-p "$PIDFILE"} "${DAEMON:-none}" "$NAME"
+	fi
 }
 
-if [ "$DEBUG" = "true" ] ; then
-    set -x
+if [ "$DEBUG" = "true" ]; then
+	set -x
 fi
 
 # Unset configuration variables to make sure that if variable is not assigned a
 # value in init script, it does not use one from environment. See #822918.
 unset DAEMON DAEMON_ARGS DESC NAME COMMAND_NAME PIDFILE \
-    RELOAD_ARGS RELOAD_SIGNAL START_ARGS STOP_ARGS SETPRIV_ARGS
+	RELOAD_ARGS RELOAD_SIGNAL START_ARGS STOP_ARGS SETPRIV_ARGS TYPE
 
 SCRIPTNAME="$__init_d_script_name"
 scriptbasename=${__init_d_script_name##*/}
-if [ "$scriptbasename" != "init-d-script" ] ; then
-    . "$__init_d_script_name"
+if [ "$scriptbasename" != "init-d-script" ]; then
+	. "$__init_d_script_name"
 else
-    exit 0
+	exit 0
 fi
 
 : ${NAME:=${DAEMON##*/}}
@@ -199,17 +224,17 @@ fi
 
 # Do not use pid file if $PIDFILE is 'none'.  Otherwise, generate from
 # $NAME or use the value provided by the init.d script.
-if [ none = "$PIDFILE" ] ; then
-    PIDFILE=
-elif [ -z "$PIDFILE" ] ; then
-    PIDFILE=/var/run/$NAME.pid
+if [ none = "$PIDFILE" ]; then
+	PIDFILE=
+elif [ -z "$PIDFILE" ]; then
+	PIDFILE=/var/run/$NAME.pid
 fi
 
 # Read configuration variable file if it is present
 [ -r "/etc/default/${NAME}" ] && . "/etc/default/${NAME}"
 
 # Exit if the package is not installed
-if [ none != "$DAEMON" ] && [ ! -x "$DAEMON" ] ; then
+if [ none != "$DAEMON" ] && [ ! -x "$DAEMON" ]; then
 	exit 0
 fi
 
@@ -219,73 +244,80 @@ fi
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
-if [ -t 0 ] ; then # Be verbose when called from a terminal
-    VERBOSE=yes
+if [ -t 0 ]; then # Be verbose when called from a terminal
+	VERBOSE=yes
 fi
 
 # Setup do_reload if not already defined
-if ! is_call_implemented do_reload ; then
-	if ! is_call_implemented do_reload_cmd && [ -n "$RELOAD_SIGNAL" ]
-	then
+if ! is_call_implemented do_reload; then
+	if ! is_call_implemented do_reload_cmd && [ -n "$RELOAD_SIGNAL" ]; then
 		do_reload_cmd() { do_reload_signal; }
 	fi
-	if is_call_implemented do_reload_cmd ; then
+	if is_call_implemented do_reload_cmd; then
 		alias do_reload=do_reload_wrapper
 	fi
 fi
 
+# Check if setpriv is available
+if [ "$SETPRIV_ARGS" ]; then
+	if ! PATH=/bin:/usr/bin command -v setpriv >/dev/null 2>&1; then
+		echo "WARNING: setpriv not available, ignoring SETPRIV_ARGS" >&2
+		unset SETPRIV_ARGS
+	fi
+fi
+
 case "$1" in
-  start)
-	call do_start
-	;;
-  stop)
-	call do_stop
-	;;
-  status)
-	call do_status
-	;;
-  reload)
-	if is_call_implemented do_reload ; then
-		do_reload
-	else
+	start)
+		call do_start
+		;;
+	stop)
+		call do_stop
+		;;
+	status)
+		call do_status
+		;;
+	reload)
+		if is_call_implemented do_reload; then
+			do_reload
+		else
+			call do_usage
+			exit 3
+		fi
+		;;
+	force-reload)
+		if is_call_implemented do_force_reload; then
+			call do_force_reload
+		elif is_call_implemented do_reload; then
+			do_reload
+		else
+			call do_restart
+		fi
+		;;
+	restart)
+		call do_restart
+		;;
+	try-restart)
+		vlog_daemon_msg "Trying to restart $DESC" "$NAME"
+		if (call do_status) >/dev/null; then
+			(call do_restart) >/dev/null
+		else
+			[ no != "$VERBOSE" ] && log_progress_msg "is not running"
+			true
+		fi
+		vlog_end_msg $?
+		;;
+	'')
 		call do_usage
 		exit 3
-	fi
-	;;
-  force-reload)
-	if is_call_implemented do_force_reload ; then
-		call do_force_reload
-	elif is_call_implemented do_reload ; then
-		do_reload
-	else
-		call do_restart
-	fi
-	;;
-  restart)
-	call do_restart
-	;;
-  try-restart)
-	vlog_daemon_msg "Trying to restart $DESC" "$NAME"
-	if (call do_status) >/dev/null ; then
-		(call do_restart) >/dev/null
-	else
-		[ no != "$VERBOSE" ] && log_progress_msg "is not running"
-		true
-    	fi
-	vlog_end_msg $?
-	;;
-  '')
-	call do_usage
-	exit 3
-	;;
-  *)
-	if is_call_implemented do_unknown ; then
-	    call do_unknown "$1"
-	    exit 3
-	else
-	    call do_usage
-	    exit 3
-	fi
-	;;
+		;;
+	*)
+		if is_call_implemented do_unknown; then
+			call do_unknown "$1"
+			exit 3
+		else
+			call do_usage
+			exit 3
+		fi
+		;;
 esac
 exit $? # See https://bugs.debian.org/822753#53
diff --git a/debian/src/initscripts/etc/init.d/bootlogs b/debian/src/initscripts/etc/init.d/bootlogs
--- a/debian/src/initscripts/etc/init.d/bootlogs
+++ b/debian/src/initscripts/etc/init.d/bootlogs
@@ -15,13 +15,13 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 [ "$DELAYLOGIN" ] || DELAYLOGIN=yes
 . /lib/init/vars.sh
 
-do_start () {
+do_start() {
 	# If /var/log/dmesg exists, rotate it, otherwise touch it with
 	# reasonable default permsissions and ownership.
 	#
 	# savelog(8) preserves ownership and permissions, that were set by
 	# local system administrator.
-	if test -f /var/log/dmesg ; then
+	if [ -f /var/log/dmesg ]; then
 		savelog -q -p -c 5 /var/log/dmesg
 	else
 		touch /var/log/dmesg
@@ -30,40 +30,38 @@ do_start () {
 	fi
 
 	# Save kernel messages in /var/log/dmesg
-	if which dmesg >/dev/null 2>&1
-	then
-		dmesg -s 524288 > /var/log/dmesg
-	elif [ -c /dev/klog ]
-	then
+	if which dmesg >/dev/null 2>&1; then
+		dmesg -s 524288 >/var/log/dmesg
+	elif [ -c /dev/klog ]; then
 		dd if=/dev/klog of=/var/log/dmesg &
 		sleep 1
 		kill $!
 	fi
 }
 
-do_status () {
+do_status() {
 	return 0
 }
 
 case "$1" in
-  start|"")
-	do_start
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop)
-	# No-op
-	;;
-  status)
-	do_status
-	exit $?
-	;;
-  *)
-	echo "Usage: bootlogs [start|stop|status]" >&2
-	exit 3
-	;;
+	start | "")
+		do_start
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop)
+		# No-op
+		;;
+	status)
+		do_status
+		exit $?
+		;;
+	*)
+		echo "Usage: bootlogs [start|stop|status]" >&2
+		exit 3
+		;;
 esac
 
 :
diff --git a/debian/src/initscripts/etc/init.d/halt b/debian/src/initscripts/etc/init.d/halt
--- a/debian/src/initscripts/etc/init.d/halt
+++ b/debian/src/initscripts/etc/init.d/halt
@@ -16,39 +16,35 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 
 . /lib/lsb/init-functions
 
-do_stop () {
-	if [ "$INIT_HALT" = "" ]
-	then
+do_stop() {
+	if [ "$INIT_HALT" = "" ]; then
 		case "$HALT" in
-		  [Pp]*)
-			INIT_HALT=POWEROFF
-			;;
-		  [Hh]*)
-			INIT_HALT=HALT
-			;;
-		  *)
-			INIT_HALT=POWEROFF
-			;;
+			[Pp]*)
+				INIT_HALT=POWEROFF
+				;;
+			[Hh]*)
+				INIT_HALT=HALT
+				;;
+			*)
+				INIT_HALT=POWEROFF
+				;;
 		esac
 	fi
 
 	# See if we need to cut the power.
-	if [ "$INIT_HALT" = "POWEROFF" ] && [ -x /etc/init.d/ups-monitor ]
-	then
+	if [ "$INIT_HALT" = "POWEROFF" ] && [ -x /etc/init.d/ups-monitor ]; then
 		/etc/init.d/ups-monitor poweroff
 	fi
 
 	# Don't shut down drives if we're using RAID.
 	hddown="-h"
-	if grep -qs '^md.*active' /proc/mdstat
-	then
+	if grep -qs '^md.*active' /proc/mdstat; then
 		hddown=""
 	fi
 
 	# If INIT_HALT=HALT don't poweroff.
 	poweroff="-p"
-	if [ "$INIT_HALT" = "HALT" ]
-	then
+	if [ "$INIT_HALT" = "HALT" ]; then
 		poweroff=""
 	fi
 
@@ -64,20 +60,20 @@ do_stop () {
 }
 
 case "$1" in
-  start|status)
-	# No-op
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop)
-	do_stop
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start | status)
+		# No-op
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop)
+		do_stop
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
 
 :
diff --git a/debian/src/initscripts/etc/init.d/killprocs b/debian/src/initscripts/etc/init.d/killprocs
--- a/debian/src/initscripts/etc/init.d/killprocs
+++ b/debian/src/initscripts/etc/init.d/killprocs
@@ -12,7 +12,7 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 
 . /lib/lsb/init-functions
 
-do_start () {
+do_start() {
 	# Kill all processes.
 	log_action_begin_msg "Asking all remaining processes to terminate"
 	killall5 -15 # SIGTERM
@@ -24,39 +24,39 @@ do_start () {
 		# value, because either killall5 work and it make
 		# sense to wait for processes to die, or it fail and
 		# there is nothing to wait for.
-		
-		if killall5 -18 ; then
-		    :
+
+		if killall5 -18; then
+			:
 		else
-		    alldead=1
-		    break
+			alldead=1
+			break
 		fi
 
 		sleep 1
 	done
-	if [ -z "$alldead" ] ; then
-	    log_action_begin_msg "Killing all remaining processes"
-	    killall5 -9 # SIGKILL
-	    log_action_end_msg 1
+	if [ -z "$alldead" ]; then
+		log_action_begin_msg "Killing all remaining processes"
+		killall5 -9 # SIGKILL
+		log_action_end_msg 1
 	else
-	    log_action_begin_msg "All processes ended within $seq seconds."
-	    log_action_end_msg 0
+		log_action_begin_msg "All processes ended within $seq seconds."
+		log_action_end_msg 0
 	fi
 }
 
 case "$1" in
-  start)
-	do_start
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop|status)
-	# No-op
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start)
+		do_start
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop | status)
+		# No-op
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
diff --git a/debian/src/initscripts/etc/init.d/rmnologin b/debian/src/initscripts/etc/init.d/rmnologin
--- a/debian/src/initscripts/etc/init.d/rmnologin
+++ b/debian/src/initscripts/etc/init.d/rmnologin
@@ -2,7 +2,7 @@
 ### BEGIN INIT INFO
 # Provides:          rmnologin
 # Required-Start:    $remote_fs
-# Required-Stop: 
+# Required-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:
 # Short-Description: Remove /run/nologin at boot
@@ -16,19 +16,19 @@ PATH=/sbin:/bin
 [ "$DELAYLOGIN" ] || DELAYLOGIN=yes
 . /lib/init/vars.sh
 
-do_start () {
+do_start() {
 	#
 	# If login delaying is enabled then remove the flag file
 	#
 	case "$DELAYLOGIN" in
-	  Y*|y*)
-		rm -f /run/nologin
-		;;
+		Y* | y*)
+			rm -f /run/nologin
+			;;
 	esac
 }
 
-do_status () {
-	if [ ! -f /run/nologin ] ; then
+do_status() {
+	if [ ! -f /run/nologin ]; then
 		return 0
 	else
 		return 4
@@ -36,24 +36,24 @@ do_status () {
 }
 
 case "$1" in
-  start)
-	do_start
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop)
-	# No-op
-	;;
-  status)
-	do_status
-	exit $?
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start)
+		do_start
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop)
+		# No-op
+		;;
+	status)
+		do_status
+		exit $?
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
 
 :
diff --git a/debian/src/initscripts/etc/init.d/single b/debian/src/initscripts/etc/init.d/single
--- a/debian/src/initscripts/etc/init.d/single
+++ b/debian/src/initscripts/etc/init.d/single
@@ -12,24 +12,24 @@ PATH=/sbin:/bin
 
 . /lib/lsb/init-functions
 
-do_start () {
+do_start() {
 	log_action_msg "Will now switch to single-user mode"
 	exec telinit S
 }
 
 case "$1" in
-  start)
-	do_start
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop|status)
-	# No-op
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start)
+		do_start
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop | status)
+		# No-op
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
diff --git a/debian/src/initscripts/etc/init.d/umountfs b/debian/src/initscripts/etc/init.d/umountfs
--- a/debian/src/initscripts/etc/init.d/umountfs
+++ b/debian/src/initscripts/etc/init.d/umountfs
@@ -16,51 +16,48 @@ PATH=/usr/sbin:/usr/bin:/sbin:/bin
 
 umask 022
 
-do_stop () {
+do_stop() {
 	PROTECTED_MOUNTS="$(sed -n ':a;/^[^ ]* \/ /!{H;n;ba};{H;s/.*//;x;s/\n//;p}' /proc/mounts)"
 	WEAK_MTPTS="" # be gentle, don't use force
 	REG_MTPTS=""
 	TMPFS_MTPTS=""
-	while read -r DEV MTPT FSTYPE REST
-	do
+	while read -r DEV MTPT FSTYPE REST; do
 		echo "$PROTECTED_MOUNTS" | grep -qsF "$DEV $MTPT " && continue
 		case "$MTPT" in
-		  /|/usr|/proc|/dev|/.dev|/dev/pts|/dev/shm|/dev/.static/dev|/proc/*|/sys|/sys/*|/run|/run/lock|/run/shm|/run/rpc_pipefs|/dev/vcs)
-			continue
-			;;
+			/ | /usr | /proc | /dev | /.dev | /dev/pts | /dev/shm | /dev/.static/dev | /proc/* | /sys | /sys/* | /run | /run/lock | /run/shm | /run/rpc_pipefs | /dev/vcs)
+				continue
+				;;
 		esac
 		case "$FSTYPE" in
-		  proc|procfs|linprocfs|sysfs|securityfs|usbfs|usbdevfs|devpts)
-			continue
-			;;
-		  tmpfs)
-			TMPFS_MTPTS="$MTPT $TMPFS_MTPTS"
-			;;
-		  *)
-			if echo "$PROTECTED_MOUNTS" | grep -qs "^$DEV "; then
-				WEAK_MTPTS="$MTPT $WEAK_MTPTS"
-			else
-				REG_MTPTS="$MTPT $REG_MTPTS"
-			fi
-			;;
+			proc | procfs | linprocfs | sysfs | securityfs | usbfs | usbdevfs | devpts)
+				continue
+				;;
+			tmpfs)
+				TMPFS_MTPTS="$MTPT $TMPFS_MTPTS"
+				;;
+			*)
+				if echo "$PROTECTED_MOUNTS" | grep -qs "^$DEV "; then
+					WEAK_MTPTS="$MTPT $WEAK_MTPTS"
+				else
+					REG_MTPTS="$MTPT $REG_MTPTS"
+				fi
+				;;
 		esac
-	done < /proc/mounts
+	done </proc/mounts
 
 	#
 	# Make sure tmpfs file systems are umounted before turning off
 	# swap, to avoid running out of memory if the tmpfs filesystems
 	# use a lot of space.
 	#
-	if [ "$TMPFS_MTPTS" ]
-	then
-		if [ "$VERBOSE" = no ]
-		then
+	if [ "$TMPFS_MTPTS" ]; then
+		if [ "$VERBOSE" = no ]; then
 			log_action_begin_msg "Unmounting temporary filesystems"
-			fstab-decode umount $TMPFS_MTPTS
+			fstab-decode umount --recursive $TMPFS_MTPTS
 			log_action_end_msg $?
 		else
 			log_daemon_msg "Will now unmount temporary filesystems"
-			fstab-decode umount -v $TMPFS_MTPTS
+			fstab-decode umount --recursive -v $TMPFS_MTPTS
 			log_end_msg $?
 		fi
 	fi
@@ -68,8 +65,7 @@ do_stop () {
 	#
 	# Deactivate swap
 	#
-	if [ "$VERBOSE" = no ]
-	then
+	if [ "$VERBOSE" = no ]; then
 		log_action_begin_msg "Deactivating swap"
 		swapoff -a >/dev/null
 		log_action_end_msg $?
@@ -84,8 +80,7 @@ do_stop () {
 	#
 	if [ "$WEAK_MTPTS" ]; then
 		# Do not use -f umount option for WEAK_MTPTS
-		if [ "$VERBOSE" = no ]
-		then
+		if [ "$VERBOSE" = no ]; then
 			log_action_begin_msg "Unmounting weak filesystems"
 			fstab-decode umount -r -d $WEAK_MTPTS
 			log_action_end_msg $?
@@ -95,10 +90,8 @@ do_stop () {
 			log_end_msg $?
 		fi
 	fi
-	if [ "$REG_MTPTS" ]
-	then
-		if [ "$VERBOSE" = no ]
-		then
+	if [ "$REG_MTPTS" ]; then
+		if [ "$VERBOSE" = no ]; then
 			log_action_begin_msg "Unmounting local filesystems"
 			fstab-decode umount -f -r -d $REG_MTPTS
 			log_action_end_msg $?
@@ -111,20 +104,20 @@ do_stop () {
 }
 
 case "$1" in
-  start|status)
-	# No-op
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop)
-	do_stop
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start | status)
+		# No-op
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop)
+		do_stop
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
 
 :
diff --git a/debian/src/initscripts/etc/init.d/umountroot b/debian/src/initscripts/etc/init.d/umountroot
--- a/debian/src/initscripts/etc/init.d/umountroot
+++ b/debian/src/initscripts/etc/init.d/umountroot
@@ -14,7 +14,7 @@ PATH=/sbin:/bin
 
 . /lib/lsb/init-functions
 
-remount_ro () {
+remount_ro() {
 	[ "$VERBOSE" = no ] || log_action_begin_msg "Mounting $1 filesystem read-only"
 	MOUNT_FORCE_OPT=
 	[ "$(uname -s)" = "GNU/kFreeBSD" ] && MOUNT_FORCE_OPT=-f
@@ -22,14 +22,14 @@ remount_ro () {
 	#     mount -n -o remount,ro /
 	# will act on a bind mount of / if there is one.
 	# See #339023 and the comment in checkroot.sh
-	mount    $MOUNT_FORCE_OPT -n -o remount,ro -t dummytype dummydev $2 2>/dev/null \
-	|| mount $MOUNT_FORCE_OPT -n -o remount,ro              dummydev $2 2>/dev/null \
-	|| mount $MOUNT_FORCE_OPT -n -o remount,ro                       $2
+	mount $MOUNT_FORCE_OPT -n -o remount,ro -t dummytype dummydev $2 2>/dev/null ||
+		mount $MOUNT_FORCE_OPT -n -o remount,ro dummydev $2 2>/dev/null ||
+		mount $MOUNT_FORCE_OPT -n -o remount,ro $2
 	ES=$?
 	[ "$VERBOSE" = no ] || log_action_end_msg $ES
 }
 
-do_stop () {
+do_stop() {
 	remount_ro root /
 	if mountpoint -q /usr; then
 		remount_ro /usr /usr
@@ -37,20 +37,20 @@ do_stop () {
 }
 
 case "$1" in
-  start|status)
-	# No-op
-	;;
-  restart|reload|force-reload)
-	echo "Error: argument '$1' not supported" >&2
-	exit 3
-	;;
-  stop)
-	do_stop
-	;;
-  *)
-	echo "Usage: $0 start|stop" >&2
-	exit 3
-	;;
+	start | status)
+		# No-op
+		;;
+	restart | reload | force-reload)
+		echo "Error: argument '$1' not supported" >&2
+		exit 3
+		;;
+	stop)
+		do_stop
+		;;
+	*)
+		echo "Usage: $0 start|stop" >&2
+		exit 3
+		;;
 esac
 
 :
diff --git a/debian/src/initscripts/etc/network/if-up.d/mountnfs b/debian/src/initscripts/etc/network/if-up.d/mountnfs
--- a/debian/src/initscripts/etc/network/if-up.d/mountnfs
+++ b/debian/src/initscripts/etc/network/if-up.d/mountnfs
@@ -35,66 +35,64 @@ set_env() {
 		if [ -f "$file" ]; then
 			while read DEV MTPT FSTYPE OPTS REST; do
 				case "$DEV" in
-				  ""|\#*)
-					continue
-					;;
+					"" | \#*)
+						continue
+						;;
 				esac
 				case "$OPTS" in
-				  noauto|*,noauto|noauto,*|*,noauto,*)
-					continue
-					;;
-				  _netdev|*,_netdev|_netdev,*|*,_netdev,*)
-					NETDEV=yes
-					;;
+					noauto | *,noauto | noauto,* | *,noauto,*)
+						continue
+						;;
+					_netdev | *,_netdev | _netdev,* | *,_netdev,*)
+						NETDEV=yes
+						;;
 				esac
 				case "$FSTYPE" in
-				  nfs)
-					# NFS filesystems normally
-					# require statd and
-					# portmap. However, if nolock
-					# is set, portmap and statd
-					# are not required for this
-					# file system.
-					case "$OPTS" in
-					  nolock|*,nolock|nolock,*|*,nolock,*)
-						# no action
-						;;
-					  *)
-						start_nfs=yes
-						;;
-					esac
-
-					# However, Kerberos requires
-					# gssd, so start nfs-common
-					# anyway.
-					case "$OPTS" in
-					  sec=krb5|*,sec=krb5|sec=krb5,*|*,sec=krb5,*|sec=krb5i|*,sec=krb5i|sec=krb5i,*|*,sec=krb5i,*|sec=krb5p|*,sec=krb5p|sec=krb5p,*|*,sec=krb5p,*)
-						start_nfs=yes
-						;;
+					nfs)
+						# NFS filesystems normally
+						# require statd and
+						# portmap. However, if nolock
+						# is set, portmap and statd
+						# are not required for this
+						# file system.
+						case "$OPTS" in
+							nolock | *,nolock | nolock,* | *,nolock,*)
+								# no action
+								;;
+							*)
+								start_nfs=yes
+								;;
 						esac
-					;;
-				  nfs4)
-					# NFSv4 requires idmapd, so
-					# start nfs-common no matter
-					# what the options are.
-					start_nfs=yes
-					;;
-				  smbfs|cifs|coda|ncp|ncpfs|ceph)
-					;;
-				  *)
-					FSTYPE=
-					;;
+
+						# However, Kerberos requires
+						# gssd, so start nfs-common
+						# anyway.
+						case "$OPTS" in
+							sec=krb5 | *,sec=krb5 | sec=krb5,* | *,sec=krb5,* | sec=krb5i | *,sec=krb5i | sec=krb5i,* | *,sec=krb5i,* | sec=krb5p | *,sec=krb5p | sec=krb5p,* | *,sec=krb5p,*)
+								start_nfs=yes
+								;;
+						esac
+						;;
+					nfs4)
+						# NFSv4 requires idmapd, so
+						# start nfs-common no matter
+						# what the options are.
+						start_nfs=yes
+						;;
+					smbfs | cifs | coda | ncp | ncpfs | ceph) ;;
+					*)
+						FSTYPE=
+						;;
 				esac
 				if [ "$FSTYPE" ]; then
 					case "$NETFS" in
-					  $FSTYPE|*,$FSTYPE|$FSTYPE,*|*,$FSTYPE,*)
-						;;
-					  *)
-						NETFS="$NETFS${NETFS:+,}$FSTYPE"
-						;;
+						$FSTYPE | *,$FSTYPE | $FSTYPE,* | *,$FSTYPE,*) ;;
+						*)
+							NETFS="$NETFS${NETFS:+,}$FSTYPE"
+							;;
 					esac
 				fi
-			done < "$file"
+			done <"$file"
 		fi
 	done
 }
@@ -105,16 +103,14 @@ do_start() {
 	# and/or rpc.idmapd, and loads the right kernel modules if
 	# applicable) if we use Kerberos and/or NFSv4 mounts.
 	#
-	if [ "$start_nfs" = yes ] && [ -x /etc/init.d/nfs-common ]
-	then
+	if [ "$start_nfs" = yes ] && [ -x /etc/init.d/nfs-common ]; then
 		[ -x /etc/init.d/portmap ] && /etc/init.d/portmap start
 		[ -x /etc/init.d/rpcbind ] && /etc/init.d/rpcbind start
 		/etc/init.d/nfs-common start
 	fi
 
 	pre_mountall
-	if [ "$NETFS" ]
-	then
+	if [ "$NETFS" ]; then
 		mount -a -t$NETFS
 	fi
 	if [ "$NETDEV" ]; then
@@ -124,17 +120,17 @@ do_start() {
 }
 
 exit_unless_last_interface() {
-    ifaces="$(ifquery --list)"
-    for i in $ifaces ; do
-	if [ "$i" = "lo" ]; then
-	    continue
-	fi
-	if ! ifquery --state $i >/dev/null ; then
-	    msg="if-up.d/mountnfs[$IFACE]: waiting for interface $i before doing NFS mounts"
-	    [ "$VERBOSE" ] && log_warning_msg "$msg"
-	    exit 0
-	fi
-    done
+	ifaces="$(ifquery --list)"
+	for i in $ifaces; do
+		if [ "$i" = "lo" ]; then
+			continue
+		fi
+		if ! ifquery --state $i >/dev/null; then
+			msg="if-up.d/mountnfs[$IFACE]: waiting for interface $i before doing NFS mounts"
+			[ "$VERBOSE" ] && log_warning_msg "$msg"
+			exit 0
+		fi
+	done
 }
 
 # Using 'no !=' instead of 'yes =' to make sure async nfs mounting is
@@ -143,35 +139,35 @@ set_env
 # Exit immediately and do not claim to wait for the last interface if
 # no network file systems are listed in /etc/fstab.
 if [ "$start_nfs" = "no" ] && [ ! "$NETFS" ] && [ ! "$NETDEV" ]; then
-  exit 0
+	exit 0
 fi
 
 if [ no != "$ASYNCMOUNTNFS" ]; then
-    # Not for loopback!
-    [ "$IFACE" != "lo" ] || exit 0
+	# Not for loopback!
+	[ "$IFACE" != "lo" ] || exit 0
 
-    [ "$ADDRFAM" = "inet" ] || [ "$ADDRFAM" = "inet6" ] || exit 0
+	[ "$ADDRFAM" = "inet" ] || [ "$ADDRFAM" = "inet6" ] || exit 0
 
-    # Wait until all auto interfaces are up before attempting to mount
-    # network file systems.
-    exit_unless_last_interface
+	# Wait until all auto interfaces are up before attempting to mount
+	# network file systems.
+	exit_unless_last_interface
 
-    on_exit() {
-        # Clean up lock when script exits, even if interrupted
-	rm -rf /run/network/mountnfs 2>/dev/null || exit 0
-    }
-    # Lock around this otherwise insanity may occur
-    mkdir /run/network          2>/dev/null || true
-    if mkdir /run/network/mountnfs 2>/dev/null ; then
-	trap on_exit EXIT # Enable cleanup handler
-    else
-	msg="if-up.d/mountnfs[$IFACE]: lock /run/network/mountnfs exists, not mounting"
-	log_failure_msg "$msg"
-	# Log if /usr/ is mounted
-	[ -x /usr/bin/logger ] && /usr/bin/logger -t "if-up.d/mountnfs[$IFACE]" "$msg"
-	exit 0
-    fi
-    do_start
-elif [ yes = "$FROMINITD" ] ; then
-    do_start
+	on_exit() {
+		# Clean up lock when script exits, even if interrupted
+		rm -rf /run/network/mountnfs 2>/dev/null || exit 0
+	}
+	# Lock around this otherwise insanity may occur
+	mkdir /run/network 2>/dev/null || true
+	if mkdir /run/network/mountnfs 2>/dev/null; then
+		trap on_exit EXIT # Enable cleanup handler
+	else
+		msg="if-up.d/mountnfs[$IFACE]: lock /run/network/mountnfs exists, not mounting"
+		log_failure_msg "$msg"
+		# Log if /usr/ is mounted
+		[ -x /usr/bin/logger ] && /usr/bin/logger -t "if-up.d/mountnfs[$IFACE]" "$msg"
+		exit 0
+	fi
+	do_start
+elif [ yes = "$FROMINITD" ]; then
+	do_start
 fi
